# Generated by Django 4.1.7 on 2023-12-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(choices=[(1, 'Worst'), (2, 'Not good'), (3, 'good'), (4, 'Better'), (5, 'Best')]),
        ),
    ]
